# Site
repository: alvionna/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alvionna Shiergetya Sunaryo
title: Research Assistant at CoAI Lab (Tsinghua University)
email: alvionna.sunaryo@gmail.com
phone: +62 812-1853-6282 / +86 185-071-155-1873
# website: www.github.com/alvionna/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alvionna
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: alvionna_ss
linkedin_username: alvionna-sunaryo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Alvionna and I'm currently pursuing Master of Science (M.Sc.) in Advanced Computing at Tsinghua University. I am also working as a research assistant at the CoAI (Conversational AI) Laboratory. My research interest lies in Natural Language Processing (NLP) and Artificial Intelligence (AI). 

  What I am trying to solve: 
  1. How to make robot/chatbot talks like us, humans? (not awkwardly and not so robotly :D) 
  2. How to make robot/chatbot understand humans emotionally? 
  3. How to create a mental health support chatbot that is accessible? 

  I am most skilled in: <mark>Python, NLP, Machine Learning</mark> and <mark>Eating Noodles</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tsinghua University
        link: coai.cs.tsinghua.edu.cn
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: January 2023 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left 
        title: Mount Holyoke College
        link: mtholyoke.edu
        additional_links:
          - title:  IMeRoLab Instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/theimerolab/
        sub_title: Research Assistant
        caption: June 2021 - May 2022
        quote: >
          WHAT YOU DO IN A FUN WAY
        description: |
          EXPERIENCE DESCIRPTION
      - layout: left 
        title: Mount Holyoke College
        link: mtholyoke.edu
        sub_title: Machine Learning Teaching Assistant
        caption: Jan 2021 - May 2022
        quote: >
          WHAT YOU DO IN A FUN WAY
        description: |
          EXPERIENCE DESCIRPTION
      - layout: left 
        title: Mount Holyoke College
        link: mtholyoke.edu
        sub_title: Intro to Computer Science Teaching Assistant 
        caption: Jan 2020 - May 2020
        quote: >
          WHAT YOU DO IN A FUN WAY
        description: |
          EXPERIENCE DESCIRPTION
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Genshin Impact Search Engine
        link: github.com/alvionna/genshin-search-engine
        # link_text: Project Website
        additional_links:
          - title:  alvionna/genshin-search-engine
            icon: fab fa-github
            url: github.com/alvionna/genshin-search-engine
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: top-middle
        title: TRACOVID (Tracking COVID-19)
        link: github.com/mhc-cs/tracovid
        # link_text: Project Website
        additional_links:
          - title: mhc-cs/tracovid
            icon: fab fa-github
            url: github.com/mhc-cs/tracovid
        quote: >
          WHATEVER
        description: | # this will include new lines to allow paragraphs
          WHAT WE DO FOR TRACOVID
      - layout: top-middle
        title: Breast Classification Project
        link: github.com/alvionna/breast-cancer-classification
        # link_text: Project Website
        additional_links:
          - title:  alvionna/breast-cancer-classification
            icon: fab fa-github
            url: github.com/alvionna/breast-cancer-classification
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mount Holyoke College
        caption: 2018 - 2022
        sub_title: B.A. in Computer Science and Mathematics (Cum Laude)
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: More about me 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and frontend, some of my other interests and hobbies are:
      - Singing
      - Dancing
      - Knitting
      - Swimming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
