# Site
repository: alvionna/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alvionna Shiergetya Sunaryo
title: Research Assistant at CoAI Lab (Tsinghua University)
email: alvionna.sunaryo@gmail.com
phone: +62 812-1853-6282 / +86 185-071-155-1873
# website: www.github.com/alvionna/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alvionna
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: alvionna_ss
linkedin_username: alvionna-sunaryo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Alvionna and I'm currently pursuing Master of Science (M.Sc.) in Advanced Computing at Tsinghua University. I am also working as a research assistant at the CoAI (Conversational AI) Laboratory. My research interest lies in Natural Language Processing (NLP) and Artificial Intelligence (AI). 

  What I am trying to solve: 
  1. How to make robot/chatbot talks like us, humans? (not awkwardly and not so robotly :D) 
  2. How to make robot/chatbot understand humans emotionally? 
  3. How to create a mental health support chatbot that is accessible? 

  I am most skilled in: <mark>Python, NLP, Machine Learning</mark> and <mark>Eating Noodles</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tsinghua University
        link: coai.cs.tsinghua.edu.cn
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: January 2023 - Present
        quote: >
          Skills: Research, NLP, LLMs, AI, Pytorch, Github, Deep Learning, Machine Learning 
        description: | # this will include new lines to allow paragraphs
           Researched and analyzed current methodologies and best practices in the field of conversational AI, resulting in the identification of key strategies to create an effective and personalized mental health support chatbot using LLMs, like GPT-3.5, LlaMa-2, etc.
      - layout: left     
        title: Mount Holyoke College
        link: mtholyoke.edu
        additional_links:
          - title:  IMeRoLab Instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/theimerolab/
        sub_title: Research Assistant
        caption: June 2021 - May 2022
        quote: >
          Skills: PyTorch, Machine Learning, TensorFlow, Teaching, Python
        description: |
          Taught students how to utilize ML libraries and frameworks, including PyTorch and Tensorflow, which resulted in an improvement in their ability to develop complex ML models. 
          
          Coordinated a weekly drop-in office hour for 18 students to review ML concepts and models, such as Logistic Regression, ANN, and CNN, leading to a 20% increase in student comprehension of ML topics.
          
          Assessed and graded the homework of the class, consisted of 18 students
      - layout: left 
        title: Mount Holyoke College
        link: mtholyoke.edu
        sub_title: Machine Learning Teaching Assistant
        caption: Jan 2021 - May 2022
        quote: >
          Skills: Artificial Intelligence (AI) · Research Skills, PyTorch, Computer Vision, GitHub, Machine Learning, Python (Programming Language)
        description: |
          Researched and analyzed recent advancements in image reconstruction literature, identifying key gaps and limitations that could be addressed to improve accuracy.
          
          Constructed a modified GAN using a combination of Siamese Network and Deep Convolutional Generative Adversarial Network (DCGAN) architecture in Pytorch.
      - layout: left 
        title: Mount Holyoke College
        link: mtholyoke.edu
        sub_title: Intro to Computer Science Teaching Assistant 
        caption: Jan 2020 - May 2020
        quote: >
          Data Structures, Teaching, Computer Science, Object-Oriented Programming (OOP)
        description: |
          Instructed a diverse group of students in the fundamentals of Python programming, covering topics such as if-else statements, arrays, dictionaries, and an introduction to Object-Oriented Programming (OOP).
         
          Conducted personalized tutoring sessions with 3 mentees on a weekly basis, resulting in an average increase of 15% in their understanding of complex computer science concepts.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Genshin Impact Search Engine
        link: github.com/alvionna/genshin-search-engine
        # link_text: Project Website
        additional_links:
          - title:  alvionna/genshin-search-engine
            icon: fab fa-github
            url: github.com/alvionna/genshin-search-engine
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Skills: JavaScript · Information Retrieval · Whoosh · React.js · HTML · Front-end Development, CSS, Flask, Github
        description: | # this will include new lines to allow paragraphs
          Implemented advanced search algorithms, including BM25 and TF-IDF ranking systems, to enhance the accuracy and relevance of search results on a search engine website for Genshin Impact.
          
          Designed and developed a user-friendly frontend interface using React.js, HTML, and CSS for a search engine website dedicated to Genshin Impact game.
          
          Integrated the Whoosh library into the backend infrastructure of the Genshin Impact search engine website, improving indexing speed and query performance.
      - layout: top-middle
        title: TRACOVID (Tracking COVID-19)
        link: github.com/mhc-cs/tracovid
        # link_text: Project Website
        additional_links:
          - title: mhc-cs/tracovid
            icon: fab fa-github
            url: github.com/mhc-cs/tracovid
        quote: >
          Skills: GitHub · Mobile Application Development · Node.js · Flutter
        description: | # this will include new lines to allow paragraphs
          Developed and implemented a cross-platform mobile application (iOS and Android) in Flutter for
          contact tracing of COVID-19 at school and tested by more than 10 students.
          
          Implemented a seamless integration process utilizing Node.js to connect the structured database
          (MySQL) with the application, resulting in improved user experience and reduced data input errors.
          
          Scraped the school's website using BeautifulSoup to gather COVID-19 news updates, resulting in an accurate and up-to-date display of the number of COVID cases and operating level at the school.
      - layout: top-middle
        title: Breast Classification Project
        link: github.com/alvionna/breast-cancer-classification
        # link_text: Project Website
        additional_links:
          - title:  alvionna/breast-cancer-classification
            icon: fab fa-github
            url: github.com/alvionna/breast-cancer-classification
        quote: >
          Skills: Artificial Intelligence (AI) · Computer Vision · GitHub · Machine Learning · TensorFlow
        description: | # this will include new lines to allow paragraphs
          Conducted comprehensive analysis of 4 machine learning models including Logistic Regression, Multiclass Classification, ANNs, and CNNs to classify breast cancer tumors.
          Developed and implemented machine learning algorithms using Tensorflow and Keras libraries, resulting in a 72.35% accuracy rate for the CNN model and a 76.26% accuracy rate for the ANN model.  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
       - layout: left
        title: Tsinghua University
        caption: 2022 - present
        sub_title: M.Sc in Advanced Computing
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: Mount Holyoke College
        caption: 2018 - 2022
        sub_title: B.A. in Computer Science and Mathematics (Cum Laude)
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: More about me 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and frontend, some of my other interests and hobbies are:
      - Singing
      - Dancing
      - Knitting
      - Swimming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
